name: Meditation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Decode and set up keystore.jks
        run: |
          echo "${{ secrets.KEYSTORE_STORE_FILE_BASE_64 }}" | base64 --decode > /home/runner/work/Invitta/Invitta/app/keystore.jks

      - name: Create local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > ./local.properties
          echo "KEYSTORE_STORE_FILE=/home/runner/work/Invitta/Invitta/app/keystore.jks" >> ./local.properties
          echo "KEYSTORE_KEY_ALIAS=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> ./local.properties
          echo "KEYSTORE_STORE_PASSWORD=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> ./local.properties
          echo "KEYSTORE_KEY_PASSWORD=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> ./local.properties

      - name: Decode and set up google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE_64 }}" | base64 --decode > ./app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Ktlint check
        run: ./gradlew ktlintCheck

      - name: Detekt validation
        run: ./gradlew detekt

      - name: Clean
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Unit tests
        run: ./gradlew testDebugUnitTest
